### PR TITLE
Brendan

### PR DESCRIPTION
**Pull request by Brendan-Leighton**
I've configured the JS to have only 1 doc.ready function as Dwayne and I each had one. All code resides in the doc.ready.

### CODE REVIEW

**Review by cjlaflamme1 — COMMENTED** [review]
I'm going to wait to merge this one until we have class tomorrow.  It looks like it modifies the index again, and I'm not sure why.

**Comment by Brendan-Leighton** [comment]
I made some changes to the submit button; added an ID and a type="button", the Type is set to Submit by default and it reloads the page upon pressing.

I know in the Head I moved the src/script.js from the bottom of Body to the Head. We added a document.ready() so the JS won't fire until after the page loads so it doesn't have to be on the bottom.

I'm gonna leave some comments in the "view changes" screen.

**Comment by cjlaflamme1** [comment]
> I made some changes to the submit button; added an ID and a type="button", the Type is set to Submit by default and it reloads the page upon pressing.
> 
> I know in the Head I moved the src/script.js from the bottom of Body to the Head. We added a document.ready() so the JS won't fire until after the page loads so it doesn't have to be on the bottom.
> 
> I'm gonna leave some comments in the "view changes" screen.

Sounds good!  I think I just don't fully understand this merging and approving process still.  Alex's had some conflicts that I reconciled, but I felt like I had no idea what I was doing, haha.  So maybe we can get one of the TAs to go through the process with us tonight.

**Review by cjlaflamme1 — APPROVED** [review]
Merging

**Pull request merged**
